package pb

// Please do not edit this file

// Validate request interceptor validator.
func (r *HelloReq) Validate() error {
	return validate.Struct(r)
}

// Validate request interceptor validator.
func (r *InfoReq) Validate() error {
	return validate.Struct(r)
}

