package pb

// Code generated by validator_gen tools.DO NOT EDIT.

// Validate HelloReq interceptor validator.
func (r *HelloReq) Validate() error {
	return validate.Struct(r)
}

// Validate InfoReq interceptor validator.
func (r *InfoReq) Validate() error {
	return validate.Struct(r)
}

