<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: hello.proto

namespace App\Grpc\GPBMetadata;

class Hello
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        // \AppGrpc\GPBMetadata\Google\Api\Annotations::initOnce();
        $pool->internalAddGeneratedFile(
            '
û
hello.protoApp.Grpc.Hello"
HelloReq

id ("+

HelloReply
name (	
message (	"
InfoReq
name (	"-
	InfoReply
address (	
message (	2½
GreeterServiceV
SayHello.App.Grpc.Hello.HelloReq.App.Grpc.Hello.HelloReply"‚Óä“/v1/say/{id}S
Info.App.Grpc.Hello.InfoReq.App.Grpc.Hello.InfoReply"‚Óä“/v1/info/{name}BZ./;pbbproto3'
        , true);

        static::$is_initialized = true;
    }
}

